### ISSUE TITLE
Dropped frames on localhost

### ISSUE THREAD

**Issue by galsasson** [elliotwoods/ofxSquashBuddies#7]
This is not really an issue but a really strange behavior that I'm seeing.
I'm trying to debug a slowdown that I have over time when sending kinect data (users' point cloud positions and colors).
I noticed that even when the sender and receiver are running on the same machine I'm still getting dropped frames. Also noticed that over time the frequency of dropped frames increases (after about an hour with a lot of data).
I was running the tests with a few different codecs including: density, lz4, and copy (no compression) and got the same result.

Is this normal? Do you have any idea what can be the cause or where to look?
Thanks!

**Comment by elliotwoods** [comment]
Hey there

If you're not getting a reliable stream with UDP
Then please try the TCP version: (requires zmq)
https://github.com/elliotwoods/ofxSquashBuddies/tree/zmq?files=1

**Comment by galsasson** [comment]
Thanks, I will give it a try.
Just an update, after further testing it appears that I was getting all these dropped frames when the receiving end is a Windows 7 machine. Almost no drop packets when using other OS.
Hopefully TCP will solve the issue. Thanks!

**Comment by elliotwoods** [comment]
Hmm interesting
Thanks for letting me know.
I should add it to readme somewhere if it's true

**Comment by galsasson** [comment]
Switching to TCP did solve my issue. It looks like Windows 7 was dropping many UDP packets for a reason I still don't know.
Thanks for pointing out to the TCP branch!
